<?php

use think\migration\Migrator;
use think\migration\db\Column;

class IniManagePermissions extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function up()
    {
        $data = array (
            0 =>
                array (
                    'id' => 1,
                    'name' => 'navigation',
                    'title' => '快捷导航',
                    'parent_id' => 0,
                    'level' => '0',
                    'icon' => 'layui-icon-at',
                    'jump' => '',
                    'spread' => 1,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            1 =>
                array (
                    'id' => 2,
                    'name' => 'home',
                    'title' => '首页',
                    'parent_id' => 1,
                    'level' => '',
                    'icon' => 'layui-icon-console',
                    'jump' => '/',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            2 =>
                array (
                    'id' => 3,
                    'name' => 'system',
                    'title' => '系统管理',
                    'parent_id' => 0,
                    'level' => '',
                    'icon' => 'layui-icon-windows',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            3 =>
                array (
                    'id' => 4,
                    'name' => 'permission',
                    'title' => '权限管理',
                    'parent_id' => 3,
                    'level' => '',
                    'icon' => 'layui-icon-layouts',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'menu',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            4 =>
                array (
                    'id' => 5,
                    'name' => 'menus',
                    'title' => '菜单管理',
                    'parent_id' => 4,
                    'level' => '4',
                    'icon' => 'layui-icon-menu-fill',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'menu@list',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            5 =>
                array (
                    'id' => 6,
                    'name' => 'roles',
                    'title' => '角色管理',
                    'parent_id' => 4,
                    'level' => '4',
                    'icon' => 'layui-icon-service',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'role@list',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            6 =>
                array (
                    'id' => 7,
                    'name' => 'departments',
                    'title' => '部门管理',
                    'parent_id' => 4,
                    'level' => '4',
                    'icon' => 'layui-icon-group',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'department@list',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            7 =>
                array (
                    'id' => 8,
                    'name' => 'jobs',
                    'title' => '岗位管理',
                    'parent_id' => 4,
                    'level' => '4',
                    'icon' => 'layui-icon-friends',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'job@list',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            8 =>
                array (
                    'id' => 9,
                    'name' => 'users',
                    'title' => '用户管理',
                    'parent_id' => 4,
                    'level' => '4',
                    'icon' => 'layui-icon-user',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'user@list',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            9 =>
                array (
                    'id' => 10,
                    'name' => 'save',
                    'title' => '保存',
                    'parent_id' => 5,
                    'level' => '4-5',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'menu@save',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            10 =>
                array (
                    'id' => 11,
                    'name' => 'select',
                    'title' => '菜单选择',
                    'parent_id' => 5,
                    'level' => '4-5',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'menu@select',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            11 =>
                array (
                    'id' => 12,
                    'name' => 'delete',
                    'title' => '删除',
                    'parent_id' => 5,
                    'level' => '4-5',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 0,
                    'permission_mark' => 'menu@del',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            12 =>
                array (
                    'id' => 13,
                    'name' => 'auth_adopt',
                    'title' => '权限白名单',
                    'parent_id' => 0,
                    'level' => '0',
                    'icon' => 'layui-icon-theme',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 1,
                    'sort' => 0,
                ),
            13 =>
                array (
                    'id' => 14,
                    'name' => 'main',
                    'title' => '主导航菜单',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => 'layui-icon-theme',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'menu@main',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            14 =>
                array (
                    'id' => 15,
                    'name' => 'select_adopt',
                    'title' => '角色选择列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => 'layui-icon-theme',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'menu@select_adopt',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            15 =>
                array (
                    'id' => 16,
                    'name' => 'list',
                    'title' => '菜单列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => 'layui-icon-theme',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'menu@list',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            16 =>
                array (
                    'id' => 17,
                    'name' => 'list',
                    'title' => '角色列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => 'layui-icon-theme',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'role',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            17 =>
                array (
                    'id' => 18,
                    'name' => 'save',
                    'title' => '角色保存',
                    'parent_id' => 6,
                    'level' => '4-6',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'role@save',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            18 =>
                array (
                    'id' => 19,
                    'name' => 'del',
                    'title' => '删除角色',
                    'parent_id' => 6,
                    'level' => '4-6',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'role@del',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            19 =>
                array (
                    'id' => 20,
                    'name' => 'del_batch',
                    'title' => '批量删除角色',
                    'parent_id' => 6,
                    'level' => '4-6',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'role@del_batch',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            20 =>
                array (
                    'id' => 21,
                    'name' => 'update_status_batch',
                    'title' => '批量更新角色状态',
                    'parent_id' => 6,
                    'level' => '4-6',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'role@update_status_batch',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            21 =>
                array (
                    'id' => 22,
                    'name' => 'select',
                    'title' => '选择角色列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'role@select',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            22 =>
                array (
                    'id' => 23,
                    'name' => 'list',
                    'title' => '部门列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'department',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            23 =>
                array (
                    'id' => 24,
                    'name' => 'save',
                    'title' => '部门保存',
                    'parent_id' => 7,
                    'level' => '4-7',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'department@save',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            24 =>
                array (
                    'id' => 25,
                    'name' => 'del',
                    'title' => '删除部门',
                    'parent_id' => 7,
                    'level' => '4-7',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'department@del',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            25 =>
                array (
                    'id' => 26,
                    'name' => 'select',
                    'title' => '选择部门',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'department@select',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            26 =>
                array (
                    'id' => 27,
                    'name' => 'list',
                    'title' => '岗位列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'job',
                    'permission_adopt' => 1,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            27 =>
                array (
                    'id' => 28,
                    'name' => 'save',
                    'title' => '保存岗位',
                    'parent_id' => 8,
                    'level' => '4-8',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'job@save',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            28 =>
                array (
                    'id' => 29,
                    'name' => 'del',
                    'title' => '删除岗位',
                    'parent_id' => 8,
                    'level' => '4-8',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'job@del',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            29 =>
                array (
                    'id' => 30,
                    'name' => 'del_batch',
                    'title' => '批量删除岗位',
                    'parent_id' => 8,
                    'level' => '4-8',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'job@del_batch',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            30 =>
                array (
                    'id' => 31,
                    'name' => 'update_status_batch',
                    'title' => '批量更新岗位状态',
                    'parent_id' => 8,
                    'level' => '4-8',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'job@update_status_batch',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            31 =>
                array (
                    'id' => 32,
                    'name' => 'list',
                    'title' => '用户(管理员)列表',
                    'parent_id' => 13,
                    'level' => '13',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'user',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            32 =>
                array (
                    'id' => 33,
                    'name' => 'save',
                    'title' => '保存用户',
                    'parent_id' => 9,
                    'level' => '4-9',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'user@save',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            33 =>
                array (
                    'id' => 34,
                    'name' => 'del',
                    'title' => '删除用户',
                    'parent_id' => 9,
                    'level' => '4-9',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'user@del',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            34 =>
                array (
                    'id' => 35,
                    'name' => 'del_batch',
                    'title' => '批量删除用户',
                    'parent_id' => 9,
                    'level' => '4-9',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'user@del_batch',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            35 =>
                array (
                    'id' => 36,
                    'name' => 'update_status_batch',
                    'title' => '批量更新用户状态',
                    'parent_id' => 9,
                    'level' => '4-9',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'user@update_status_batch',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            36 =>
                array (
                    'id' => 37,
                    'name' => 'config',
                    'title' => '配置管理',
                    'parent_id' => 3,
                    'level' => '3',
                    'icon' => 'layui-icon-set',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            37 =>
                array (
                    'id' => 38,
                    'name' => 'user',
                    'title' => '个人资料',
                    'parent_id' => 37,
                    'level' => '3-37',
                    'icon' => 'layui-icon-face-smile-fine',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            38 =>
                array (
                    'id' => 39,
                    'name' => 'info',
                    'title' => '基本资料',
                    'parent_id' => 38,
                    'level' => '37-38',
                    'icon' => '',
                    'jump' => '/system/config/user/info',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            39 =>
                array (
                    'id' => 40,
                    'name' => 'password',
                    'title' => '修改密码',
                    'parent_id' => 38,
                    'level' => '37-38',
                    'icon' => '',
                    'jump' => '/system/config/user/password',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            40 =>
                array (
                    'id' => 41,
                    'name' => 'list',
                    'title' => '配置列表',
                    'parent_id' => 37,
                    'level' => '3-37',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            41 =>
                array (
                    'id' => 42,
                    'name' => 'site',
                    'title' => '网站设置',
                    'parent_id' => 37,
                    'level' => '3-37',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            42 =>
                array (
                    'id' => 43,
                    'name' => 'upload',
                    'title' => '上传配置',
                    'parent_id' => 37,
                    'level' => '3-37',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            43 =>
                array (
                    'id' => 44,
                    'name' => 'config',
                    'title' => '列表',
                    'parent_id' => 41,
                    'level' => '3-37-41',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'config',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            44 =>
                array (
                    'id' => 45,
                    'name' => 'save',
                    'title' => '保存',
                    'parent_id' => 41,
                    'level' => '3-37-41',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => 'config@save',
                    'permission_adopt' => 2,
                    'type' => 2,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            45 =>
                array (
                    'id' => 46,
                    'name' => 'upload',
                    'title' => '上传管理',
                    'parent_id' => 0,
                    'level' => '0',
                    'icon' => 'layui-icon-upload-drag',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            46 =>
                array (
                    'id' => 47,
                    'name' => 'images',
                    'title' => '图片资源',
                    'parent_id' => 46,
                    'level' => '46',
                    'icon' => 'layui-icon-picture',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            47 =>
                array (
                    'id' => 48,
                    'name' => 'portal',
                    'title' => '门户管理',
                    'parent_id' => 0,
                    'level' => '0',
                    'icon' => 'layui-icon-layouts',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            48 =>
                array (
                    'id' => 49,
                    'name' => 'navigation',
                    'title' => '导航管理',
                    'parent_id' => 48,
                    'level' => '48',
                    'icon' => 'layui-icon-find-fill',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
            49 =>
                array (
                    'id' => 50,
                    'name' => 'main',
                    'title' => '主导航',
                    'parent_id' => 49,
                    'level' => '48-49',
                    'icon' => '',
                    'jump' => '',
                    'spread' => 2,
                    'creator_id' => 1,
                    'permission_mark' => '',
                    'permission_adopt' => 2,
                    'type' => 1,
                    'hidden' => 2,
                    'sort' => 0,
                ),
        );

        $this->table('manage_permissions')->insert($data)->saveData();
    }
}
